FROM python:3.10.5-alpine3.16 AS build

RUN mkdir /app/
WORKDIR /app/

COPY ./src/requirements.txt /app/requirements.txt
RUN pip install -r requirements.txt

COPY ./src/ /app/

ENV FLASK_APP=server.py
EXPOSE 8000
EXPOSE 5000
CMD flask run -h 0.0.0.0 -p 5000